### ISSUE TITLE
evcli login does not properly reset the terminal environment upon error

### ISSUE THREAD

**Issue by adyxax** [exograd/eventline#5]
As stated in the description, if `evcli login` can not complete, the terminal ends up in a broken state where characters are no longer echoed, forcing the end user to run the `reset` command.

## Steps to reproduce

Simulating a failed login attempt reproduces this issue 100% using the evcli binary from github's v1.0.0 release page:
```sh
$ evcli login
API endpoint: http://lore:8085
Username: admin
Password:
logging in to http://lore:8085
error: cannot log in: cannot send request: Post "http://lore:8085/login": dial tcp 10.1.2.5:8085: connect: no route to host
```

After this error, characters are no longer echoed to the terminal.

**Comment by galdor** [comment]
Fixed in branch `v1.0`.
