### ISSUE TITLE
Unable login in http mode

### ISSUE THREAD

**Issue by aunoor** [exograd/eventline#6]
Attribute 'Secure' in response cookies prevent setting 'session_id' cookie when eventline started in http-only mode.

**Comment by galdor** [comment]
Sorry about the delay, I did not receive any GitHub notification.

Out of localhost, we only support HTTPS deployments for security reasons. Do you have a specific setup in mind?

**Comment by aunoor** [comment]
Hi.
Thanks for answer.
Scenario is simple: on-premise install  with no access from outside of corporate network. Because network is trusted, there is no need for https.

**Comment by galdor** [comment]
Even in a corporate network this would be very dangerous since Eventline expose credentials stored in identities.

I imagine I could add an option, making it very clear that this is horribly unsecure. Would it work for you?

**Comment by aunoor** [comment]
Yes, that would be a very useful option.
And as for security, there are scenarios where it is not possible to use a full-fledged certificate, for example, in a small corporate network or even at home network, and using a self-signed one can do more harm than be usefull.
Thanks!

**Comment by galdor** [comment]
Got it, I'll try to add it soon.

**Comment by galdor** [comment]
I just pushed a patch adding a new `insecure_http_cookies` top-level configuration option. Can you try `master` with this option set to `true` and tell me if it works for you?
